"""users table

Revision ID: 5d9d1f18ec24
Revises: 9fbaf2742878
Create Date: 2021-02-24 12:57:39.214260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9d1f18ec24'
down_revision = '9fbaf2742878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markup_filename'), 'markup', ['filename'], unique=False)
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_authenticated')
    op.drop_column('user', 'is_anonymous')
    op.drop_column('user', 'is_active')
    op.drop_index(op.f('ix_markup_filename'), table_name='markup')
    op.drop_table('markup')
    # ### end Alembic commands ###
